# Generated by Django 3.2.4 on 2021-07-15 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0002_room_beds'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='size',
            field=models.CharField(choices=[('small', 'Small'), ('medium', 'Medium'), ('large', 'Large')], default='small', max_length=20),
            preserve_default=False,
        ),
    ]
