# Generated by Django 3.2.4 on 2021-07-28 00:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0003_room_size'),
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='room',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='rooms.room'),
        ),
    ]
