# Generated by Django 3.2.4 on 2021-07-28 03:00

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0003_room_size'),
        ('booking', '0004_alter_booking_check_in_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='scheduled_room',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scheduled_room', to='rooms.room'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
