# Generated by Django 3.2.4 on 2021-07-28 03:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0003_room_size'),
        ('booking', '0005_auto_20210728_0300'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='scheduled_room',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scheduled_booking', to='rooms.room'),
        ),
    ]
