# Generated by Django 3.2.12 on 2022-02-06 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0007_auto_20220205_1845'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='is_active',
        ),
        migrations.AddField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('new', 'New'), ('scheduled', 'Scheduled'), ('checked_in', 'Checked-In'), ('completed', 'Completed')], default='new', max_length=20),
        ),
    ]
